### ISSUE TITLE
Turnstile non-interactive / invisible rendering

### ISSUE THREAD

**Issue by DerSimeon** [nuxt-modules/turnstile#196]
### 🆒 Your use case

I would like to be able to use the invisible turnstile, which cloudflare offers.

### 🆕 The solution you'd like

As per their docs
here : https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#appearance-modes 
& and here: https://developers.cloudflare.com/turnstile/reference/widget-types/#invisible 
and also as per the turnstile configuration on the cloudflare dashboard, it is possible to make the rendering non-interactive or invisible. As of right now nuxt-modules/turnstile is missing this option which forces me to have the big cloudflare widget on my page.

**Comment by dargmuesli** [comment]
cc @PatrickMi, sounds familiar to our requirements

**Comment by dargmuesli** [comment]
True, it does work for me by simply changing the option selected in the cloudflare dashboard. Closing this for now, but this issue can be reopened if necessary!
