### ISSUE TITLE
Wrong Nuxt Module Documentation Link

### ISSUE THREAD

**Issue by nicokempe** [nuxt-modules/turnstile#248]
### 📚 Is your documentation request related to a problem?

I guess the Module documentation for the module overview on Nuxt is referring to the GitHub Readme file. This caused at least the "[See all options](https://nuxt.com/modules/src/runtime/types.ts)" link not to work from the Nuxt module description.
![here](https://github.com/nuxt-modules/turnstile/assets/50241630/cdba35df-eb9c-4365-8b95-2f3cdde88bc5)
![grafik](https://github.com/nuxt-modules/turnstile/assets/50241630/b8e57816-5a1e-487d-b016-eb29a7144913)
![grafik](https://github.com/nuxt-modules/turnstile/assets/50241630/6e9addad-9dca-4528-9b1a-3df417891553)

### 🔍 Where should you find it?

https://nuxt.com/modules/turnstile

**Comment by dargmuesli** [comment]
I've created #249 as a suggestion on how to get the links fixed :)
