### ISSUE TITLE
Callback loop with `NuxtTurnstile`

### ISSUE THREAD

**Issue by huang-julien** [nuxt-modules/turnstile#267]
### 🐛 The bug

When changing the page, the turnstile box isn't properly removed and causing and infinite loop. 

to reproduce it on the reproduction, 

- go to the form page
- load the turnstile iframes
- wait for it 
- navigate back to the homepage
- open your console
- check your logs

### 🛠️ To reproduce

https://stackblitz.com/edit/github-cuqope?file=pages%2Findex.vue,pages%2Fform.vue

### 🌈 Expected behaviour

we shouldn't have any warning log

### ℹ️ Additional context

I can take it, already fixed on my project :)

**Comment by dargmuesli** [comment]
I noticed that too, recently. If you want feel free to submit a PR! <3

**Comment by huang-julien** [comment]
sure !

**Comment by iammello** [comment]
Waiting for fixing.

**Comment by huang-julien** [comment]
Oops for those interested here's the workaround atm, 
within `onBeforeUnmount` of the compoennt wrapper `NuxtTurnstile`
`window.turnstile.remove(`str`)` where str is the wrapper selector + `div`
ex:
````ts
onBeforeUnmount(() => {
  window.turnstile.remove('#turnstile-wrapper div')
})

````
