### ISSUE TITLE
Uncaught (in promise) ReferenceError: nextTick is not defined

### ISSUE THREAD

**Issue by madebyfabian** [nuxt-modules/turnstile#273]
### 🐛 The bug

Hi there! After the update on 0.6.0, the widget stopped rendering and I get these console logs:

![Bildschirmfoto 2023-08-27 um 20 54 25](https://github.com/nuxt-modules/turnstile/assets/32813692/ece5ec31-5591-4251-b851-6b400aa512ab)

You can reproduce it by opening the playground link.

### 🛠️ To reproduce

https://stackblitz.com/github/nuxt-modules/turnstile/tree/main/playground?file=package.json

### 🌈 Expected behaviour

Everything should work like before 😄

**Comment by dargmuesli** [comment]
My bad, I removed `nextTick` first, not knowing why it was required, then readded it with a comment explaining why it's needed but forgetting to readd the import statement. Should be fixed now!
I'm in contact with @danielroe about release permissions so either he'll create a release or I'll do once the permissions are granted.

**Comment by madebyfabian** [comment]
@dargmuesli no worries, thank you so much!

**Comment by AleexMzz** [comment]
Hello, don't forget to update npmjs, thank you very much.

**Comment by dargmuesli** [comment]
Should be pushed to npm now! :raised_hands:
I'm currently setting up a new ci pipeline and am trying to combine the best of two worlds :wink: somehow the push to npm got lost in the void, but now it's there.
