### ISSUE TITLE
perf: load script only on pages where it is used

### ISSUE THREAD

**Issue by avi-agg** [nuxt-modules/turnstile#288]
### 📚 Is your documentation request related to a problem?

By default the Script is being loaded on all pages. I want it to load on selected pages. How can I do that?,

**Comment by dargmuesli** [comment]
I think [the plugin's functionality to load the script](https://github.com/nuxt-modules/turnstile/blob/b966b1b8e96220973d8730e06fab14af3f745065/src/runtime/plugins/script.ts#L89) would need to be moved to the `NuxtTurnstile` component. Before I say "pull request welcome" though, I'd like to ask @danielroe if there is any reason to keep the head extension in the plugin.

**Comment by danielroe** [comment]
Yes, I think it would be nice to move it to the component, if we can implement it so it's deduplicated across components and also not _removed_ from the head if the component is unmounted (as this could result in the script being loaded more than once).

**Comment by lucasuracosta** [comment]
+1

**Comment by dargmuesli** [comment]
I think this is a good task for a community PR, help welcome! :raised_hands:

**Comment by dargmuesli** [comment]
@danielroe did #306 help to resolve this issue or is this unrelated?

**Comment by danielroe** [comment]
yes, this should be resolved!
