### ISSUE TITLE
Cannot find module '@nuxt/scripts'

### ISSUE THREAD

**Issue by markus-gx** [nuxt-modules/turnstile#319]
### 🐛 The bug

After upgrading to the latest Version `0.9.0` the error: 
```
 ERROR  Error while requiring module @nuxt/scripts: Error: Cannot find module '@nuxt/scripts'                                                                                                                                                                                                     9:27:00 AM

```

is thrown when starting nuxt. 

It seems to be related to #306 

--- After adding `@nuxt/scripts` in the project the problem is resolved. 

### 🛠️ To reproduce

.

### 🌈 Expected behaviour

.

**Comment by dargmuesli** [comment]
This is intended behavior, `@nuxtjs/turnstile` now requires `@nuxt/scripts`.
