### ISSUE TITLE
Module broken if we use @nuxt/script > v0.6.0 

### ISSUE THREAD

**Issue by XStarlink** [nuxt-modules/turnstile#320]
### 🐛 The bug

[The release of @nuxt/scripts v0.6.0 here](https://github.com/nuxt/scripts/releases/tag/v0.6.0) introduced some breaking changes, impacting @nuxtjs/turnstile which now throws this error:

`useElementScriptTrigger` is provided by @nuxt/scripts. Check your console to install it or run 'npx nuxi@latest module add @nuxt/scripts' to install it.

This is normal as some composables have been renamed, but I just wanted to let you know here

### 🛠️ To reproduce

.

### 🌈 Expected behaviour

The module should load without errors

**Comment by dargmuesli** [comment]
Thank you for the heads up, I've [limited the supported version range](a9de1c50833109a6dc058b4ba641440242bb55fe) for now as there seems to be another issue with @nuxt/scripts v6.0.2: https://github.com/nuxt/scripts/issues/133
