### ISSUE TITLE
Internal server error: [unimport] failed to find "useScriptTriggerElement" imported from "#imports" 

### ISSUE THREAD

**Issue by onurgultekin** [nuxt-modules/turnstile#323]
### 🐛 The bug

Internal server error: [unimport] failed to find "useScriptTriggerElement" imported from "#imports" 

### 🛠️ To reproduce

Just run yarn generate or yarn dev, it does not work.

### 🌈 Expected behaviour

We have to get no errors.

### ℹ️ Additional context

Node version: 18.19.0

Nuxt 3.12.3 with Nitro 2.9.7   

Internal server error: [unimport] failed to find "useScriptTriggerElement" imported from "#imports" 
Plugin: nuxt:imports-transform

 ERROR  Pre-transform error: [unimport] failed to find "useScriptTriggerElement" imported from "#imports"

 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/node_modules/@nuxtjs/turnstile/dist/runtime/components/NuxtTurnstile.vue"

**Comment by danielroe** [comment]
You might need to update the version of Nuxt Scripts you have installed.

**Comment by onurgultekin** [comment]
@danielroe I am using Nuxt version 3.12.3 and turnstile version 0.9.3 and getting the same error during yarn generate and yarn dev.
