### ISSUE TITLE
fix: callbacks don't seem to be working

### ISSUE THREAD

**Issue by Chippd** [nuxt-modules/turnstile#334]
### 📚 What are you trying to do?

Trying to manage error and success callbacks as per the documentation, but passing them to options don't seem to do anything. 

### 🔍 What have you tried?

I've read the docs and tried appending 'data-' etc. I've also looked through the source code and can't find why the options aren't being passed. 

### ℹ️ Additional context

Reproduction here: https://stackblitz.com/edit/github-tncybc?file=pages%2Findex.vue

**Comment by dargmuesli** [comment]
Thank you for the reproduction! Please try version `0.9.6` (ffe9ab2831725a0145fe4002e67c6bdd1eef1311)

**Comment by Chippd** [comment]
Much appreciated, I can confirm the callback now works for me as of 0.9.10. 

Thank you for your work
