### ISSUE TITLE
Typecheck error coming from this module

### ISSUE THREAD

**Issue by Yizack** [nuxt-modules/turnstile#336]
### 🐛 The bug

When installing this module in a clean Nuxt app and running the typecheck command `npx vue-tsc --noEmit` it shows the following error in console

![Screenshot 2024-09-18 203857](https://github.com/user-attachments/assets/148e9981-4534-4424-80fd-8f7b9bd09d9a)

### 🛠️ To reproduce

https://stackblitz.com/edit/github-qaxbsn

1. Wait for install and dev commands to run
2. Execute `npx vue-tsc --noEmit` in console

### 🌈 Expected behaviour

Shouldn't show an error

### ℹ️ Additional context

- nuxt: 3.13.2
- vue-tsc: 2.1.6
- @nuxtjs/turnstile: 0.9.6

**Comment by dargmuesli** [comment]
I'm unsure how to fix this properly, @danielroe may I ask for your assistance?

**Comment by Yizack** [comment]
I managed to have a fix for this but I'm unsure if this is the right approach

By adding this in `/src/module.ts`

https://github.com/nuxt-modules/turnstile/blob/146cad49e1b4339f7dbf07c786b48bec86e7e907/src/module.ts#L128-L131

and moving `@types/cloudflare-turnstile` from `devDependencies` to `dependencies`

https://github.com/nuxt-modules/turnstile/blob/146cad49e1b4339f7dbf07c786b48bec86e7e907/package.json#L55-L60

With these changes we get rid of the type error in a fresh install

**Comment by danielroe** [comment]
You're right, it should be a dependency!

Is that sufficient?

Please do open a PR - I will amend as necessary 🙏

**Comment by Yizack** [comment]
@danielroe it is sufficient! I'm doing it right now!

**Comment by dargmuesli** [comment]
Hmm, [I still get this type error in the most recent release](https://github.com/dargmuesli/jonas-thelemann/actions/runs/10985942075/job/30498575934?pr=458#step:7:751).

Updated reproduction: https://stackblitz.com/edit/github-qaxbsn-xvnqnd?file=package.json

**Comment by danielroe** [comment]
seems reference is being stripped somehow

**Comment by Yizack** [comment]
@danielroe 

I'm sorry, I thought it was solved with my change, but I noticed in the previous version `0.9.7` if I have the `.npmrc` file it doesn't log any error (it did in `0.9.6` now it's logging the error back in `0.9.8`)

I didn't test without the `.npmrc` file previously

Reproduction: https://stackblitz.com/edit/github-qaxbsn-sal6jg?file=.npmrc,package.json

**Comment by danielroe** [comment]
I believe this is now hotfixed in https://github.com/nuxt-modules/turnstile/commit/839cbfcfa912beadfc3927381a507752bfbdda9f.

**Comment by Yizack** [comment]
It's fixed for me, thank you for addressing the issue!
