### ISSUE TITLE
TurnstileError: [Cloudflare Turnstile] Invalid type for parameter "container", expected "string" or an implementation of "HTMLElement".

### ISSUE THREAD

**Issue by WuChenDi** [nuxt-modules/turnstile#342]
### 🐛 The bug

Hello everyone, I apologize for the interruption.

I have a question: I encountered no issues using Turnstile in my frontend project.

However, when I use it on another page, I experience the following error during page transitions.

For instance, when both `app/pages/login.vue` and `app/pages/signup.vue` utilize the `NuxtTurnstile` component, the subsequent error arises. In the development environment, the page appears blank, while in the deployed version, the page displays correctly but fails to show the verification widget.

```
VM113320 api.js:1 Uncaught (in promise) TurnstileError: [Cloudflare Turnstile] Invalid type for parameter "container", expected "string" or an implementation of "HTMLElement".
```

![image](https://github.com/user-attachments/assets/5dffe7bf-a483-4332-bef0-9b3c5e96ce4c)

### 🛠️ To reproduce

https://github.com/cdLab996/turnstile-examples-nuxt

### 🌈 Expected behaviour

It is anticipated to be displayed correctly across multiple pages.

![image](https://github.com/user-attachments/assets/894eee44-caf1-4cd7-bf16-4f14188afe3b)

**Comment by WuChenDi** [comment]
This is my current approach. However, I am aware that it is not the most effective method.

https://github.com/cdLab996/turnstile-examples-nuxt/commit/1aac4e17cb143ac723c3616566a838a83c11fbdf

**Comment by onurgultekin** [comment]
Is there any update about this? I facing the same issue on our project.

**Comment by dargmuesli** [comment]
@danielroe it appears that just [using `onLoaded`](https://github.com/nuxt-modules/turnstile/pull/338/files#diff-bc1c2b688c03023c444393cabce8b293da4e7cf5cdba97ef256748cdee6183f9R49) leads to this issue. On route change `onLoaded` seems to called before the element to mount into is available (as it's not mounted?). Does that sound plausible to you or should `onLoaded` not be the issue?

**Comment by dargmuesli** [comment]
I've created PR https://github.com/nuxt-modules/turnstile/pull/344 for now until it is determined what the proper solution should look like (maybe it already is the proper solution). You should be able to install `v0.9.11-beta.1` to check this fix.

**Comment by onurgultekin** [comment]
Thanks [dargmuesli](https://github.com/dargmuesli) I will try it out now.

**Comment by onurgultekin** [comment]
[dargmuesli](https://github.com/dargmuesli) it seems fixed. Thanks!

**Comment by arshx86** [comment]
Still goin on, @dargmuesli thanks for temporarily fix.
